config/routes.rb
Rails.application.routes.draw do
  # get '/turn', {to: "motors#on}"
  get "turn", to: "motors#on"
  get "cars", to: "cars#index"
  get "cars/new", to: "cars#new"
  post "cars", to: "cars#create"
  get "cars/:id", to: "cars#show", as: "car"
  resources :dogs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  def index
    @cars = Car.all
  end

  def new

  end

  def create
    Car.create(car_params)
    redirect_to '/cars'
  end

  def show
    @car = Car.find(params[:id])
  end

  private
    def car_params
      params.require(:car).permit(:name)
    end






end

app/controllers/motors_controller.rb
class MotorsController < ApplicationController

  def on
  # render plain: "Hola mundo"
    render plain: "Hola mundo"
  end










end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/index.html.erb
<h1>Llegaste al index de Cars</h1>

<ul>
  <%@cars.each do |car|%>
    <!-- <li>
      <a href="/cars/<%= car.id %>"><%= car.name%> </a>
    </li> -->
    <li>
      <%= link_to car.name, car_path(car) %>
    </li>
  <%end%>
</ul>

app/views/cars/new.html.erb
<h1>Llegaste a new!</h1>

<%= form_tag("/cars", method:"post") do %>
  <%= text_field(:car, :name)%>
  <%= submit_tag("Crear Carro") %>
<% end %>

app/views/cars/show.html.erb
<h1>Mi carro es: <%= @car.name %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cars</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>